# Generated by Django 5.2.9 on 2026-02-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="title",
            options={
                "ordering": ["-year", "name"],
                "verbose_name": "Произведение",
                "verbose_name_plural": "Произведения",
            },
        ),
        migrations.AlterField(
            model_name="title",
            name="duration_min",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Длительность"
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="kp_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, unique=True, verbose_name="КиноПоиск ID"
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="kp_url",
            field=models.URLField(
                blank=True, default="", max_length=500, verbose_name="КиноПоиск URL"
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="title",
            name="poster_url",
            field=models.URLField(
                blank=True, default="", max_length=500, verbose_name="Ссылка на постер"
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="type",
            field=models.CharField(
                choices=[("movie", "Movie"), ("series", "Series")],
                db_index=True,
                max_length=16,
                verbose_name="Тип",
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="year",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Год"
            ),
        ),
        migrations.AddIndex(
            model_name="title",
            index=models.Index(fields=["year"], name="media_title_year_da5060_idx"),
        ),
    ]
