# Generated by Django 5.2.9 on 2026-02-15 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0002_alter_title_options_alter_title_duration_min_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Franchise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название франшизы"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Франшиза",
                "verbose_name_plural": "Франшизы",
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(verbose_name="Номер сезона"),
                ),
                (
                    "episodes_count",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Количество серий"
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasons",
                        to="media.title",
                        verbose_name="Произведение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сезон",
                "verbose_name_plural": "Сезоны",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(verbose_name="Номер серии"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Название серии",
                    ),
                ),
                (
                    "duration_min",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Длительность (мин)"
                    ),
                ),
                (
                    "air_date",
                    models.DateField(blank=True, null=True, verbose_name="Дата выхода"),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="media.season",
                        verbose_name="Сезон",
                    ),
                ),
            ],
            options={
                "verbose_name": "Серия",
                "verbose_name_plural": "Серии",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position_seconds",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Позиция (сек)"
                    ),
                ),
                (
                    "current_season_number",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Текущий сезон"
                    ),
                ),
                (
                    "current_episode_number",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Текущая серия"
                    ),
                ),
                (
                    "current_episode_position_seconds",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Позиция в серии (сек)"
                    ),
                ),
                (
                    "last_watched_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последний просмотр"
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="media.title",
                        verbose_name="Произведение",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогресс просмотра",
                "verbose_name_plural": "Прогресс просмотра",
            },
        ),
        migrations.CreateModel(
            name="UserTitleState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Запланировано"),
                            ("watching", "Смотрю"),
                            ("completed", "Просмотрено"),
                            ("dropped", "Заброшено"),
                            ("on_hold", "На паузе"),
                        ],
                        default="planned",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Оценка"
                    ),
                ),
                (
                    "review",
                    models.TextField(blank=True, default="", verbose_name="Отзыв"),
                ),
                (
                    "started_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата начала просмотра"
                    ),
                ),
                (
                    "finished_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата завершения"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_states",
                        to="media.title",
                        verbose_name="Произведение",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Состояние просмотра",
                "verbose_name_plural": "Состояния просмотра",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="FranchiseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(verbose_name="Порядковый номер"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Примечание",
                    ),
                ),
                (
                    "franchise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="media.franchise",
                        verbose_name="Франшиза",
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="franchise_items",
                        to="media.title",
                        verbose_name="Произведение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент франшизы",
                "verbose_name_plural": "Элементы франшизы",
                "indexes": [
                    models.Index(
                        fields=["franchise", "order"],
                        name="media_franc_franchi_b43cb6_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("franchise", "title"), name="uq_franchise_title"
                    ),
                    models.UniqueConstraint(
                        fields=("franchise", "order"), name="uq_franchise_order"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="season",
            index=models.Index(
                fields=["title", "number"], name="media_seaso_title_i_5b55a9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="season",
            constraint=models.UniqueConstraint(
                fields=("title", "number"), name="uq_title_season_number"
            ),
        ),
        migrations.AddIndex(
            model_name="episode",
            index=models.Index(
                fields=["season", "number"], name="media_episo_season__b61abd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="episode",
            constraint=models.UniqueConstraint(
                fields=("season", "number"), name="uq_season_episode_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="userprogress",
            constraint=models.UniqueConstraint(
                fields=("user", "title"), name="uq_user_title_progress"
            ),
        ),
        migrations.AddIndex(
            model_name="usertitlestate",
            index=models.Index(
                fields=["user", "status"], name="media_usert_user_id_40afa6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="usertitlestate",
            constraint=models.UniqueConstraint(
                fields=("user", "title"), name="uq_user_title_state"
            ),
        ),
    ]
