# Generated by Django 6.0 on 2026-02-15 20:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0003_franchise_season_episode_userprogress_usertitlestate_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserEpisodeState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("watched", models.BooleanField(default=False, verbose_name="Просмотрено")),
                ("watched_at", models.DateTimeField(blank=True, null=True, verbose_name="Когда просмотрено")),
            ],
            options={
                "verbose_name": "Состояние эпизода",
                "verbose_name_plural": "Состояния эпизодов",
            },
        ),
        migrations.AddField(
            model_name="title",
            name="category",
            field=models.CharField(
                choices=[
                    ("movie", "Фильм"),
                    ("series", "Сериал"),
                    ("anime", "Аниме"),
                    ("cartoon", "Мультфильм"),
                    ("other", "Другое"),
                ],
                db_index=True,
                default="other",
                max_length=16,
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="usertitlestate",
            name="rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)],
                verbose_name="Оценка",
            ),
        ),
        migrations.AddConstraint(
            model_name="usertitlestate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("rating__isnull", True), models.Q(("rating__gte", 0), ("rating__lte", 10)), _connector="OR"
                ),
                name="ck_user_title_state_rating_0_10",
            ),
        ),
        migrations.AddField(
            model_name="userepisodestate",
            name="episode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_states",
                to="media.episode",
                verbose_name="Эпизод",
            ),
        ),
        migrations.AddField(
            model_name="userepisodestate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Пользователь"
            ),
        ),
        migrations.AddIndex(
            model_name="userepisodestate",
            index=models.Index(fields=["user", "watched"], name="media_usere_user_id_57bc7e_idx"),
        ),
        migrations.AddConstraint(
            model_name="userepisodestate",
            constraint=models.UniqueConstraint(fields=("user", "episode"), name="uq_user_episode_state"),
        ),
    ]
