# Generated by Django 6.0 on 2026-02-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0004_userepisodestate_title_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="title",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Произведение",
                "verbose_name_plural": "Произведения",
            },
        ),
        migrations.RemoveIndex(
            model_name="title",
            name="media_title_type_11d631_idx",
        ),
        migrations.AlterField(
            model_name="title",
            name="category",
            field=models.CharField(
                choices=[
                    ("film", "Фильм"),
                    ("series", "Сериал"),
                    ("anime", "Аниме"),
                    ("cartoon", "Мультфильм"),
                    ("other", "Другое"),
                ],
                db_index=True,
                default="other",
                max_length=16,
                verbose_name="Категория",
            ),
        ),
        migrations.AddIndex(
            model_name="title",
            index=models.Index(fields=["category"], name="media_title_categor_a7b5f3_idx"),
        ),
        migrations.RemoveField(
            model_name="title",
            name="type",
        ),
    ]
