# Generated by Django 6.0 on 2026-02-19

from django.db import migrations, models


def backfill_is_series(apps, schema_editor):
    Title = apps.get_model("media", "Title")
    Title.objects.filter(category="series").update(is_series=True)


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0005_alter_title_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="title",
            name="is_series",
            field=models.BooleanField(
                default=False,
                help_text="Истина для сериалов и аниме-сериалов — подтягиваются сезоны и серии.",
                verbose_name="Сериал (есть сезоны/серии)",
            ),
        ),
        migrations.RunPython(backfill_is_series, migrations.RunPython.noop),
    ]
