# Generated by Django 6.0 on 2026-06-08 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0006_title_is_series"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="title",
            name="age_limit",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Например: age16, age18.",
                max_length=16,
                verbose_name="Возрастное ограничение",
            ),
        ),
        migrations.AddField(
            model_name="title",
            name="countries",
            field=models.JSONField(blank=True, default=list, help_text="Список названий стран.", verbose_name="Страны"),
        ),
        migrations.AddField(
            model_name="title",
            name="cover_url",
            field=models.URLField(blank=True, default="", max_length=500, verbose_name="Обложка (широкая)"),
        ),
        migrations.AddField(
            model_name="title",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="title",
            name="end_year",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Год окончания (сериал)"),
        ),
        migrations.AddField(
            model_name="title",
            name="genres",
            field=models.JSONField(blank=True, default=list, help_text="Список названий жанров.", verbose_name="Жанры"),
        ),
        migrations.AddField(
            model_name="title",
            name="imdb_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=32, verbose_name="IMDb ID"),
        ),
        migrations.AddField(
            model_name="title",
            name="original_name",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Оригинальное название"),
        ),
        migrations.AddField(
            model_name="title",
            name="rating_imdb",
            field=models.FloatField(blank=True, null=True, verbose_name="Рейтинг IMDb"),
        ),
        migrations.AddField(
            model_name="title",
            name="rating_kp",
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name="Рейтинг КиноПоиск"),
        ),
        migrations.AddField(
            model_name="title",
            name="short_description",
            field=models.TextField(blank=True, default="", verbose_name="Краткое описание"),
        ),
        migrations.AddField(
            model_name="title",
            name="slogan",
            field=models.CharField(blank=True, default="", max_length=500, verbose_name="Слоган"),
        ),
        migrations.AddField(
            model_name="title",
            name="start_year",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Год начала (сериал)"),
        ),
        migrations.CreateModel(
            name="ProviderPayload",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(db_index=True, max_length=32, verbose_name="Провайдер")),
                ("external_id", models.PositiveIntegerField(verbose_name="Внешний ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[("film", "Фильм"), ("seasons", "Сезоны"), ("search", "Поиск")],
                        max_length=16,
                        verbose_name="Тип ответа",
                    ),
                ),
                (
                    "query",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Заполняется только для kind=search.",
                        max_length=255,
                        verbose_name="Поисковый запрос",
                    ),
                ),
                ("payload", models.JSONField(verbose_name="Сырой ответ (JSON)")),
                ("fetched_at", models.DateTimeField(auto_now=True, verbose_name="Когда получено")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Когда создано")),
            ],
            options={
                "verbose_name": "Ответ провайдера",
                "verbose_name_plural": "Ответы провайдеров (кэш)",
                "ordering": ["-fetched_at"],
                "indexes": [
                    models.Index(fields=["provider", "kind"], name="media_provi_provide_744d29_idx"),
                    models.Index(fields=["provider", "query"], name="media_provi_provide_b1afba_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("provider", "external_id", "kind"), name="uq_provider_payload")
                ],
            },
        ),
        migrations.CreateModel(
            name="UserTablePreferences",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "visible_columns",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Список ключей колонок в порядке отображения.",
                        verbose_name="Видимые колонки",
                    ),
                ),
                ("page_size", models.PositiveSmallIntegerField(default=50, verbose_name="Размер страницы")),
                (
                    "view_mode",
                    models.CharField(
                        default="table", help_text="table | grid", max_length=16, verbose_name="Режим отображения"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table_preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки таблицы",
                "verbose_name_plural": "Настройки таблицы",
            },
        ),
    ]
